/*
 * struct.h -- structure of objects known to the interpreter
 */


#ifndef _STRUCT_H_
#define _STRUCT_H_


#define CLASSCHAR_HASPOINTERS		0x8000
#define CLASSCHAR_ISINDEXABLE		0x4000
#define CLASSCHAR_NUMBERMASK		0x00FF

#define SUPERCLASS_IN_METACLASS		0
#define METHODDICTIONARY_IN_METACLASS	1
#define CHARACTERISTIC_IN_METACLASS	2
#define NAME_IN_METACLASS		3
#define INSTVARS_IN_METACLASS		4
#define SIZE_OF_METACLASS		5

#define SUPERCLASS_IN_CLASS		0
#define METHODDICTIONARY_IN_CLASS	1
#define CHARACTERISTIC_IN_CLASS		2
#define NAME_IN_CLASS			3
#define INSTVARS_IN_CLASS		4
#define SIZE_OF_CLASS			5

#define SELECTOR_IN_COMPILEDMETHOD	0
#define PRIMITIVE_IN_COMPILEDMETHOD	1
#define NUMBERARGS_IN_COMPILEDMETHOD	2
#define TEMPSIZE_IN_COMPILEDMETHOD	3
#define STACKSIZE_IN_COMPILEDMETHOD	4
#define BYTECODES_IN_COMPILEDMETHOD	5
#define LITERALS_IN_COMPILEDMETHOD	6
#define SOURCEOFFSET_IN_COMPILEDMETHOD	7
#define SOURCELENGTH_IN_COMPILEDMETHOD	8
#define SIZE_OF_COMPILEDMETHOD		9

#define INSTPTR_IN_CONTEXT		1
#define STACKPTR_IN_CONTEXT		2
#define STACK_IN_CONTEXT		3

#define SENDER_IN_METHODCONTEXT		0
#define INSTPTR_IN_METHODCONTEXT	INSTPTR_IN_CONTEXT
#define STACKPTR_IN_METHODCONTEXT	STACKPTR_IN_CONTEXT
#define STACK_IN_METHODCONTEXT		STACK_IN_CONTEXT
#define CLASS_IN_METHODCONTEXT		4
#define METHOD_IN_METHODCONTEXT		5
#define RECEIVER_IN_METHODCONTEXT	6
#define TEMPORARIES_IN_METHODCONTEXT	7
#define SIZE_OF_METHODCONTEXT		8

#define CALLER_IN_BLOCKCONTEXT		0
#define INSTPTR_IN_BLOCKCONTEXT		INSTPTR_IN_CONTEXT
#define STACKPTR_IN_BLOCKCONTEXT	STACKPTR_IN_CONTEXT
#define STACK_IN_BLOCKCONTEXT		STACK_IN_CONTEXT
#define NUMBERARGS_IN_BLOCKCONTEXT	4
#define INITIALIP_IN_BLOCKCONTEXT	5
#define HOME_IN_BLOCKCONTEXT		6
#define SIZE_OF_BLOCKCONTEXT		7

#define KEY_IN_ASSOCIATION		0
#define VALUE_IN_ASSOCIATION		1
#define SIZE_OF_ASSOCIATION		2

#define NEXTLINK_IN_LINKEDOBJECT	0
#define OBJECT_IN_LINKEDOBJECT		1
#define SIZE_OF_LINKEDOBJECT		2

#define ASSOCIATIONS_IN_DICTIONARY	0
#define SIZE_OF_DICTIONARY		1


#endif /* _STRUCT_H_ */
